### ISSUE TITLE
Setting image as background-image

### ISSUE THREAD

**Issue by iandesmet** [iandesmet/maak-het-persoonlijk-frontend#9]
![Screenshot 2021-04-26 at 16 53 31](https://user-images.githubusercontent.com/56590984/116103500-ef58e480-a6af-11eb-9dde-8c5a780b2a22.png)

![Screenshot 2021-04-26 at 16 55 40](https://user-images.githubusercontent.com/56590984/116103829-3e067e80-a6b0-11eb-9ab8-3665482b0168.png)

Hoe kan ik ervoor zorgen dat de image niet in het component 'Photos.js' komt maar wordt doorgegeven aan 'Layout.js' om daar de imageURL in te stellen als backgroundimage?

**Comment by benoitboucart** [comment]
Dag Ian,

Je kan hiervoor gebruik maken van React Context om een algemene setting in op te slaan. Zie ook video hierover: https://leho-howest.instructure.com/courses/9545/pages/topics-videos?module_item_id=316643

Je kan een state aanmaken in je context (vb. photo) en die kan je dan aanpassen in je Photos.js component (setPhoto functie in de state van je context uitvoeren). 

Hier is er nog een gelijkaardig voorbeeld hierover:
https://www.warambil.com/how-to-switch-themes-with-usecontext
